## NumPy

`NumPy (Numerical Python) is a powerful library in Python used for numerical computing. It provides a multi-dimensional array object (ndarray) and functions for mathematical operations, linear algebra, statistics, and more.`

NumPy in Pytorch

In [8]:
#Numpy Array to Tensor

import torch
import numpy as np

array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array)

array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [9]:
array.dtype, tensor.dtype

(dtype('float64'), torch.float64)

Notice: float64 is not tensor's default data-type [it should've been float32].

float64 is actually NumPy's default data type

In [13]:
#Type Casting to float32

tensor = torch.tensor(array, dtype=torch.float32)
tensor2 = torch.from_numpy(array).type(torch.float32)
tensor, tensor.dtype, tensor2, tensor2.dtype

(tensor([1., 2., 3., 4., 5., 6., 7.]),
 torch.float32,
 tensor([1., 2., 3., 4., 5., 6., 7.]),
 torch.float32)

When changes done to a tensor converted from an NumPy array, changes don't reflect as they share different memory location

In [14]:
tensor = torch.from_numpy(array)
array = array + 1
tensor, array

(tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64),
 array([2., 3., 4., 5., 6., 7., 8.]))

In [16]:
#Tensor to Numpy Array

newTensor = torch.ones(6)
newArray = newTensor.numpy()

newTensor, newArray, newArray.dtype, newTensor.dtype

(tensor([1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1.], dtype=float32),
 dtype('float32'),
 torch.float32)

NumPy array inherits the default data type [float32] of tensor

And just like before the converted data is allocated new memory. Any changes on one doesn't reflect on the other

## REPRODUCIBILITY
[Trying to take random out of random]

`To reduce randomness in neural networks and PyTorch *Random Seed* is used. Random Seed gives a flavour of randomness`

`A random seed is a fixed starting point for generating random numbers, ensuring reproducibility in machine learning experiments.`

Why Use a Random Seed?
- Ensures reproducibility in ML experiments
- Helps in debugging by producing the same results

`A random seed initializes a pseudorandom number generator (PRNG) with a fixed starting state. Since PRNGs generate numbers based on mathematical formulas rather than true randomness, setting the same seed ensures the same sequence of numbers is produced every time.`

Note: `The type of randomness that generates truly unpredictable values is called "True Randomness" or "True Random Number Generation (TRNG)".`

In [22]:
#True Randomness

randomA = torch.rand(3, 4)
randomB = torch.rand(3, 4)

randomA, randomB, randomA == randomB

(tensor([[0.0613, 0.6413, 0.4626, 0.1726],
         [0.4179, 0.1342, 0.0650, 0.0922],
         [0.4748, 0.5750, 0.7290, 0.9815]]),
 tensor([[0.0233, 0.6250, 0.1925, 0.6868],
         [0.2909, 0.0068, 0.0689, 0.4902],
         [0.6820, 0.1635, 0.6918, 0.3873]]),
 tensor([[False, False, False, False],
         [False, False, False, False],
         [False, False, False, False]]))

In [25]:
#Psuedo Randomness

import torch

RANDOM_SEED = 69
torch.manual_seed(RANDOM_SEED)

radnomC = torch.rand(3, 4)
randomD = torch.rand(3, 4)

radnomC, randomD, radnomC == randomD

(tensor([[0.8398, 0.8042, 0.1213, 0.5309],
         [0.6646, 0.4077, 0.0888, 0.2429],
         [0.7053, 0.6216, 0.9188, 0.0185]]),
 tensor([[0.8741, 0.0560, 0.9659, 0.0073],
         [0.3628, 0.4197, 0.6444, 0.0099],
         [0.5925, 0.9631, 0.6958, 0.9157]]),
 tensor([[False, False, False, False],
         [False, False, False, False],
         [False, False, False, False]]))

In [27]:
#Psuedo Randomness

import torch

RANDOM_SEED = 69
torch.manual_seed(RANDOM_SEED)

radnomC = torch.rand(3, 4)

torch.manual_seed(RANDOM_SEED)      #Random seed reset to get the same result as before
randomD = torch.rand(3, 4)

radnomC, randomD, radnomC == randomD

(tensor([[0.8398, 0.8042, 0.1213, 0.5309],
         [0.6646, 0.4077, 0.0888, 0.2429],
         [0.7053, 0.6216, 0.9188, 0.0185]]),
 tensor([[0.8398, 0.8042, 0.1213, 0.5309],
         [0.6646, 0.4077, 0.0888, 0.2429],
         [0.7053, 0.6216, 0.9188, 0.0185]]),
 tensor([[True, True, True, True],
         [True, True, True, True],
         [True, True, True, True]]))