Introduction To Tensors

A tensor is a mathematical object that generalizes scalars, vectors, and matrices to higher dimensions. In simple terms, a tensor is an n-dimensional array or a multi-dimensional matrix used to represent data in machine learning, deep learning, and scientific computing.

Scalar (0-D Tensor):

A single number.
Example: 5.0, 42, -3

Vector (1-D Tensor):

A one-dimensional array of numbers.
Example: [1, 2, 3], [0.1, 0.2, 0.3]

Matrix (2-D Tensor):

A two-dimensional array (rows and columns).
Example:
[[1, 2],
[3, 4]]

Higher-dimensional Tensors (n-D Tensors):

Tensors with 3 or more dimensions, used in deep learning and more complex data representations.
Example (3D tensor): A batch of 2 images, each of 3x4 pixels with RGB channels

[[[r1, g1, b1], [r2, g2, b2], [r3, g3, b3], [r4, g4, b4]],
 [[r5, g5, b5], [r6, g6, b6], [r7, g7, b7], [r8, g8, b8]]]


In [1]:
import torch
print(torch.__version__)
print(torch.cuda.is_available())

c:\Users\LENOVO\AppData\Local\Programs\Python\Python312\Lib\site-packages\torch\_subclasses\functional_tensor.py:275: UserWarning: Failed to initialize NumPy: No module named 'numpy' (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\pytorch\torch\csrc\utils\tensor_numpy.cpp:81.)
  cpu = _conversion_method_template(device=torch.device("cpu"))


2.6.0+cpu
False


SCALAR

In [2]:
scalar = torch.tensor(7)
scalar

tensor(7)

*Dimension of a scalar is 0*

In [3]:
scalar.ndim

0

Extracting value

In [4]:
scalar.item()

7

VECTORS

In [5]:
vector = torch.tensor([4, 1, 3, 2])
vector

tensor([4, 1, 3, 2])

In [6]:
print(vector.ndim)
print(vector.shape)
print(vector.size())
#Size and Shape are different version of the same thing

1
torch.Size([4])
torch.Size([4])


MATRIX

In [7]:
matrix = torch.tensor([[1, 3, 2], [3, 3, 1], [5, 3, 2]])
matrix

tensor([[1, 3, 2],
        [3, 3, 1],
        [5, 3, 2]])

In [8]:
print(matrix.ndim)
print(matrix.shape)
print(matrix.size())
for i in matrix:
    print(i)

2
torch.Size([3, 3])
torch.Size([3, 3])
tensor([1, 3, 2])
tensor([3, 3, 1])
tensor([5, 3, 2])


TENSOR

In [9]:
tensor = torch.tensor([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(tensor)
print(tensor.ndim)
print(tensor.shape)
print(tensor[0])

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
2
torch.Size([3, 3])
tensor([1, 2, 3])


In [10]:
tensor = torch.tensor([[[1, 2, 3], [4, 5, 6], [7, 8, 9]]])
print(tensor)
print(tensor.ndim)
print(tensor.shape)
print(tensor[0])

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])
3
torch.Size([1, 3, 3])
tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])


In [11]:
tensor = torch.tensor([[[[1, 2, 3], [4, 5, 6], [7, 8, 9]]]])
print(tensor)
print(tensor.ndim)
print(tensor.shape)
print(tensor[0])

tensor([[[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]])
4
torch.Size([1, 1, 3, 3])
tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])


In [12]:
longerTensor = torch.tensor([[[[1, 2, 3], [4, 5, 6], [7, 8, 9]], [[1, 2, 3], [4, 5, 6], [7, 8, 9]]]])
print(longerTensor)
print(longerTensor.ndim)
print(longerTensor.shape)

tensor([[[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]],

         [[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]])
4
torch.Size([1, 2, 3, 3])


Random Tensors in PyTorch

In PyTorch, random tensors are tensors filled with random values.

Practical Use Cases for Random Tensors

Many neural networks learn by starting with full of random numbers and then adjust those random numbers to better represent the data

Start with Random Numbers -> Look At Data -> Update Random Numbers -> Look At Data -> Update Random Numbers -> ...

In [13]:
#Create a Random Tensor of size 2x3x4
randomTensor = torch.rand(2, 3, 4)
randomTensor

tensor([[[0.4437, 0.6053, 0.1924, 0.7387],
         [0.8984, 0.4453, 0.1067, 0.5444],
         [0.1900, 0.4050, 0.8005, 0.4282]],

        [[0.1551, 0.6791, 0.9705, 0.3677],
         [0.8292, 0.9093, 0.2107, 0.8941],
         [0.4052, 0.9145, 0.0562, 0.3174]]])

Any Data can be written as Tensors.

For example an image of 256x256 resolution will have a tensor of [3, 256, 256] size in RGB color channels

In [14]:
randomImgSizeTensor = torch.rand(size = (3, 256, 256))
randomImgSizeTensor

tensor([[[0.4788, 0.3380, 0.4646,  ..., 0.6585, 0.2157, 0.3523],
         [0.1027, 0.4059, 0.7165,  ..., 0.9989, 0.2665, 0.2644],
         [0.7088, 0.9397, 0.5347,  ..., 0.2180, 0.3394, 0.0371],
         ...,
         [0.9942, 0.5686, 0.5203,  ..., 0.4048, 0.0973, 0.2456],
         [0.0654, 0.3632, 0.2024,  ..., 0.6251, 0.6417, 0.3014],
         [0.0434, 0.9214, 0.7713,  ..., 0.6021, 0.8250, 0.3111]],

        [[0.5297, 0.9274, 0.6935,  ..., 0.0456, 0.1575, 0.5116],
         [0.3112, 0.1420, 0.2795,  ..., 0.1992, 0.7600, 0.9885],
         [0.8220, 0.7118, 0.8123,  ..., 0.7935, 0.8633, 0.0341],
         ...,
         [0.3546, 0.3109, 0.3284,  ..., 0.1866, 0.9737, 0.3098],
         [0.3009, 0.9579, 0.7969,  ..., 0.1078, 0.1470, 0.6075],
         [0.4562, 0.0292, 0.5107,  ..., 0.1396, 0.6653, 0.5243]],

        [[0.6899, 0.3423, 0.3573,  ..., 0.6974, 0.9042, 0.7648],
         [0.5445, 0.0246, 0.2013,  ..., 0.2013, 0.4484, 0.8952],
         [0.1486, 0.5638, 0.6403,  ..., 0.4623, 0.7634, 0.

In [15]:
#Tensor of all zeroes
tensorOfZeroes = torch.zeros(3, 3)
tensorOfZeroes

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [16]:
#Tensor of all ones
tensorOfOnes = torch.ones(3, 3)
tensorOfOnes

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

Tensors use 32-bit float as its default datatype

In [17]:
tensorOfOnes.dtype

torch.float32

Creating Range of Tensors and Tensors-like

torch.arange(start, end, step) -> stores values from start to (end-1)

Tensors-like -> Creates a new tensor of the same shape.

torch.zeros_like(x)

torch.ones_like(x)

torch.rand_like(x)

torch.randn_like(x)

torch.full_like(x, value)

In [18]:
oneToTen = torch.arange(start = 0, end = 12, step = 2)
# or oneToTen = torch.arange(0, 12, 2)
oneToTen

tensor([ 0,  2,  4,  6,  8, 10])

In [19]:
#Creatinng tensors-like
tenZeros = torch.zeros_like(oneToTen)
tenZeros

tensor([0, 0, 0, 0, 0, 0])