## Introduction To Tensors

`A tensor is a mathematical object that generalizes scalars, vectors, and matrices to higher dimensions. In simple terms, a tensor is an n-dimensional array or a multi-dimensional matrix used to represent data in machine learning, deep learning, and scientific computing.`

*Scalar (0-D Tensor):*

`A single number.`
`Example:` 5.0, 42, -3

*Vector (1-D Tensor):*

`A one-dimensional array of numbers.`
`Example:` [1, 2, 3], [0.1, 0.2, 0.3]

*Matrix (2-D Tensor):*

`A two-dimensional array (rows and columns).`
`Example:`

[[1, 2],
[3, 4]]

*Higher-dimensional Tensors (n-D Tensors):*

`Tensors with 3 or more dimensions, used in deep learning and more complex data representations.`
`Example (3D tensor): A batch of 2 images, each of 3x4 pixels with RGB channels`

*[[[r1, g1, b1], [r2, g2, b2], [r3, g3, b3], [r4, g4, b4]],
 [[r5, g5, b5], [r6, g6, b6], [r7, g7, b7], [r8, g8, b8]]]*


In [142]:
print(torch.__version__)
print(torch.cuda.is_available())

2.6.0+cpu
False


## SCALAR

In [143]:
scalar = torch.tensor(7)
scalar

tensor(7)

## *Dimension of a scalar is 0*

In [144]:
scalar.ndim

0

## Extracting value

In [145]:
scalar.item()

7

## VECTORS

In [146]:
vector = torch.tensor([4, 1, 3, 2])
vector

tensor([4, 1, 3, 2])

In [147]:
print(vector.ndim)
print(vector.shape)
print(vector.size())
#Size and Shape are different version of the same thing

1
torch.Size([4])
torch.Size([4])


## MATRIX

In [148]:
matrix = torch.tensor([[1, 3, 2], [3, 3, 1], [5, 3, 2]])
matrix

tensor([[1, 3, 2],
        [3, 3, 1],
        [5, 3, 2]])

In [149]:
print(matrix.ndim)
print(matrix.shape)
print(matrix.size())
for i in matrix:
    print(i)

2
torch.Size([3, 3])
torch.Size([3, 3])
tensor([1, 3, 2])
tensor([3, 3, 1])
tensor([5, 3, 2])


## TENSOR

In [150]:
tensor = torch.tensor([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(tensor)
print(tensor.ndim)
print(tensor.shape)
print(tensor[0])

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
2
torch.Size([3, 3])
tensor([1, 2, 3])


In [151]:
tensor = torch.tensor([[[1, 2, 3], [4, 5, 6], [7, 8, 9]]])
print(tensor)
print(tensor.ndim)
print(tensor.shape)
print(tensor[0])

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])
3
torch.Size([1, 3, 3])
tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])


In [152]:
tensor = torch.tensor([[[[1, 2, 3], [4, 5, 6], [7, 8, 9]]]])
print(tensor)
print(tensor.ndim)
print(tensor.shape)
print(tensor[0])

tensor([[[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]])
4
torch.Size([1, 1, 3, 3])
tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])


In [153]:
longerTensor = torch.tensor([[[[1, 2, 3], [4, 5, 6], [7, 8, 9]], [[1, 2, 3], [4, 5, 6], [7, 8, 9]]]])
print(longerTensor)
print(longerTensor.ndim)
print(longerTensor.shape)

tensor([[[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]],

         [[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]])
4
torch.Size([1, 2, 3, 3])


## Random Tensors in PyTorch

`In PyTorch, random tensors are tensors filled with random values.`

`Practical Use Cases for Random Tensors`

`Many neural networks learn by starting with full of random numbers and then adjust those random numbers to better represent the data`

`Start with Random Numbers -> Look At Data -> Update Random Numbers -> Look At Data -> Update Random Numbers -> ...`

In [154]:
#Create a Random Tensor of size 2x3x4
randomTensor = torch.rand(2, 3, 4)
randomTensor

tensor([[[0.3312, 0.0752, 0.3149, 0.6542],
         [0.6939, 0.1515, 0.0265, 0.8937],
         [0.7700, 0.5684, 0.2044, 0.6173]],

        [[0.7816, 0.3948, 0.1487, 0.0305],
         [0.0695, 0.4194, 0.7581, 0.0148],
         [0.8432, 0.8567, 0.3361, 0.8295]]])

`Any Data can be written as Tensors.`

`For example an image of 256x256 resolution will have a tensor of [3, 256, 256] size in RGB color channels`

In [155]:
randomImgSizeTensor = torch.rand(size = (3, 256, 256))
randomImgSizeTensor

tensor([[[0.6067, 0.0517, 0.8803,  ..., 0.0791, 0.3062, 0.9022],
         [0.1285, 0.1336, 0.9994,  ..., 0.3022, 0.6162, 0.8821],
         [0.9649, 0.6898, 0.9435,  ..., 0.9102, 0.8853, 0.0873],
         ...,
         [0.9492, 0.4058, 0.4100,  ..., 0.1793, 0.5575, 0.8032],
         [0.3533, 0.3713, 0.5042,  ..., 0.4452, 0.1972, 0.3207],
         [0.9569, 0.7967, 0.7882,  ..., 0.6855, 0.2490, 0.8941]],

        [[0.0985, 0.0263, 0.1336,  ..., 0.2715, 0.4140, 0.9128],
         [0.4862, 0.0247, 0.9674,  ..., 0.2547, 0.1478, 0.2932],
         [0.1959, 0.8216, 0.6547,  ..., 0.5267, 0.4169, 0.1866],
         ...,
         [0.4436, 0.2666, 0.9630,  ..., 0.0274, 0.6244, 0.0792],
         [0.3397, 0.5430, 0.4454,  ..., 0.6859, 0.1008, 0.0789],
         [0.7304, 0.1514, 0.2206,  ..., 0.7399, 0.9886, 0.8150]],

        [[0.5399, 0.7644, 0.7460,  ..., 0.3654, 0.8150, 0.6719],
         [0.1575, 0.2952, 0.4967,  ..., 0.9371, 0.8906, 0.4719],
         [0.1857, 0.0155, 0.1253,  ..., 0.6926, 0.5427, 0.

In [156]:
#Tensor of all zeroes
tensorOfZeroes = torch.zeros(3, 3)
tensorOfZeroes

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [157]:
#Tensor of all ones
tensorOfOnes = torch.ones(3, 3)
tensorOfOnes

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

`Tensors use 32-bit float as its default datatype`

In [158]:
tensorOfOnes.dtype

torch.float32

`Creating Range of Tensors and Tensors-like`

`torch.arange(start, end, step) -> stores values from start to (end-1)`

`Tensors-like -> Creates a new tensor of the same shape.`

`torch.zeros_like(x)`

`torch.ones_like(x)`

`torch.rand_like(x)`

`torch.randn_like(x)`

`torch.full_like(x, value)`

In [159]:
oneToTen = torch.arange(start = 0, end = 12, step = 2)
# or oneToTen = torch.arange(0, 12, 2)
oneToTen

tensor([ 0,  2,  4,  6,  8, 10])

In [160]:
#Creatinng tensors-like
tenZeros = torch.zeros_like(oneToTen)
tenZeros

tensor([0, 0, 0, 0, 0, 0])

## TENSOR DATA TYPES

Tensors have float_32 [torch.float32] set as default datatype

use float_64 [torch.float64 / torch.double] for higher precision
use float_16 [torch.float16 / torch.half] for half precision

3 most common error with Tensors in Pytorch and Deep Learning:
1) Tensor is not the right data type
2) Tensor is not the right shape
3) Tensor not on the right device

In PyTorch, tensors can be stored on different devices, such as:

CPU (default)
GPU (CUDA)

requires_grad – Enabling Autograd

PyTorch has an automatic differentiation engine called Autograd.
If requires_grad=True, PyTorch tracks operations on the tensor, allowing gradient computation.
Used for backpropagation in deep learning.

In [161]:
float32Tensor = torch.tensor([1, 2, 3], 
                            dtype = None,           #specify data type
                            device = "cpu",         #"cuda" for GPU
                            requires_grad = False)  #Whether or not to track the gradient for this tensor's operation
float32Tensor

tensor([1, 2, 3])

`PyTorch's device parameter is essential for controlling where tensors are stored and computations are performed. Since modern hardware includes both CPU and GPU, specifying the device ensures efficient use of available resources.`

`CPU (Central Processing Unit): General-purpose, good for small computations but slower for deep learning.`
`GPU (Graphics Processing Unit): Optimized for parallel computations, significantly faster for matrix operations (used in deep learning).`

In [162]:
#Conversion of Tensor data types

float16Tensor = float32Tensor.type(torch.float16)
float16Tensor

tensor([1., 2., 3.], dtype=torch.float16)

## TENSON OPERATIONS

- Addition
- Subtraction
- Multiplication [element-wise]
- Division
- Matrix Multiplication

In [163]:
#Scalar operations

x = torch.tensor([1, 3, 5])
print(x + 10)
print(x - 10)
print(x * 10)
print(x / 10)

print(torch.add(x, 10))
print(torch.sub(x, 10))
print(torch.mul(x, 10))
print(torch.div(x, 10))

tensor([11, 13, 15])
tensor([-9, -7, -5])
tensor([10, 30, 50])
tensor([0.1000, 0.3000, 0.5000])
tensor([11, 13, 15])
tensor([-9, -7, -5])
tensor([10, 30, 50])
tensor([0.1000, 0.3000, 0.5000])


In [164]:
#Operations among tensors

y = torch.tensor([2, 4, 6])
print(x + y)
print(x - y)

#Element-wise multiplication
print(x * y)

print(x / y)

tensor([ 3,  7, 11])
tensor([-1, -1, -1])
tensor([ 2, 12, 30])
tensor([0.5000, 0.7500, 0.8333])


In [165]:
#Matrix Multiplication

a = torch.tensor([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
b = torch.tensor([[9, 8, 7], [6, 5, 4], [3, 2, 1]])

torch.matmul(a, b)

tensor([[ 30,  24,  18],
        [ 84,  69,  54],
        [138, 114,  90]])

In [166]:
torch.mm(a, b) #Short form of matrix multiplication

tensor([[ 30,  24,  18],
        [ 84,  69,  54],
        [138, 114,  90]])

## Transpose of a Tensor

In matrix multiplication the number of columns of first Matrix must be equal to the number of rows of second matrix.
For example: 3 x 2 and 3 x 2 matrices can't be multiplied.

Again for any Matrix 'A', A and Transpose(A) can alway be multiplied

In [167]:
newTensor = torch.tensor([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(newTensor)
print(newTensor.T)

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
tensor([[1, 4, 7],
        [2, 5, 8],
        [3, 6, 9]])


Finding Min, Max, Mean, Sum etc of A Tensor

In [168]:
x = torch.rand(1, 10)
x

tensor([[0.0606, 0.0411, 0.9788, 0.2781, 0.1825, 0.9915, 0.4756, 0.1290, 0.4479,
         0.4566]])

In [169]:
x.min(), torch.min(x), torch.argmin(x) #argmin returns the index of the minimum value

(tensor(0.0411), tensor(0.0411), tensor(1))

In [170]:
x.max(), torch.max(x), torch.argmax(x)

(tensor(0.9915), tensor(0.9915), tensor(5))

In [171]:
#torch.mean() works only on float data type tensors

torch.mean(x), x.mean()

(tensor(0.4042), tensor(0.4042))

In [172]:
x.sum(), torch.sum(x)

(tensor(4.0416), tensor(4.0416))

## RESHAPING TENSORS

In [173]:
import torch

x = torch.tensor([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
x, x.size()

(tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]), torch.Size([10]))

In [174]:
reshapedX = x.reshape(5, 2)
reshaedX2 = x.reshape(2, 5)
reshaedX3 = x.reshape(1, 5, 2)  # The product of the dimensions of new shape must equal to the number of elements in original tensor
reshapedX, reshaedX2, reshaedX3

(tensor([[ 1,  2],
         [ 3,  4],
         [ 5,  6],
         [ 7,  8],
         [ 9, 10]]),
 tensor([[ 1,  2,  3,  4,  5],
         [ 6,  7,  8,  9, 10]]),
 tensor([[[ 1,  2],
          [ 3,  4],
          [ 5,  6],
          [ 7,  8],
          [ 9, 10]]]))

## VIEW OF A TENSOR

View of a tensor shares the same memory as the original's. Any change to the view will also reflect on the original tensor

In [175]:
z = x.view(2, 5)
z[0][0] = -2    #Changes in z will reflect in x
z, x

(tensor([[-2,  2,  3,  4,  5],
         [ 6,  7,  8,  9, 10]]),
 tensor([-2,  2,  3,  4,  5,  6,  7,  8,  9, 10]))

In [176]:
z = x.view(2, 5).clone()
z[0][0] = 100    #Changes in z will not reflect in x
z, x

(tensor([[100,   2,   3,   4,   5],
         [  6,   7,   8,   9,  10]]),
 tensor([-2,  2,  3,  4,  5,  6,  7,  8,  9, 10]))

## STACKING

In PyTorch, stacking refers to combining multiple tensors along a new dimension.

dim=0 inserts a new first dimension, treating each tensor as a row.
dim=1 inserts a new second dimension, treating each tensor as a column.


In [177]:
a = torch.tensor([1, 2, 3])
b = torch.tensor([4, 5, 6])
c = torch.tensor([7, 8, 9])

stackedTensor = torch.stack((a, b, c), dim = 0)
horizontalStack = torch.hstack((a, b, c))
verticalStack = torch.vstack((a, b, c))
stackedTensor, horizontalStack, verticalStack

(tensor([[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]),
 tensor([1, 2, 3, 4, 5, 6, 7, 8, 9]),
 tensor([[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]))

In [178]:
a = torch.rand(1, 2, 4)
b = torch.rand(1, 2, 4)
c = torch.rand(1, 2, 4)

stackedTensor2 = torch.stack((a, b, c), dim = 0)
stackedTensor3 = torch.stack((a, b, c), dim = 1)
stackedTensor4 = torch.stack((a, b, c), dim = 2)
stackedTensor5 = torch.stack((a, b, c), dim = 3)

a, b, c, stackedTensor2, a.shape, stackedTensor2.shape, stackedTensor3.shape, stackedTensor4.shape, stackedTensor5.shape

(tensor([[[0.1732, 0.1936, 0.1672, 0.3273],
          [0.9236, 0.6194, 0.6882, 0.7438]]]),
 tensor([[[0.2291, 0.9694, 0.8220, 0.7518],
          [0.1917, 0.9843, 0.6805, 0.3522]]]),
 tensor([[[0.3493, 0.5354, 0.3456, 0.4287],
          [0.1974, 0.5514, 0.6252, 0.1514]]]),
 tensor([[[[0.1732, 0.1936, 0.1672, 0.3273],
           [0.9236, 0.6194, 0.6882, 0.7438]]],
 
 
         [[[0.2291, 0.9694, 0.8220, 0.7518],
           [0.1917, 0.9843, 0.6805, 0.3522]]],
 
 
         [[[0.3493, 0.5354, 0.3456, 0.4287],
           [0.1974, 0.5514, 0.6252, 0.1514]]]]),
 torch.Size([1, 2, 4]),
 torch.Size([3, 1, 2, 4]),
 torch.Size([1, 3, 2, 4]),
 torch.Size([1, 2, 3, 4]),
 torch.Size([1, 2, 4, 3]))

If there are n number of dimensions in the stacked tensors, we can use dim = from (-n) to (n-1)

in the example, there are three 1 x 2 x 4 tensors.

Using dim = 0 results in a tensor of three 1 x 2 x 4 tensors [on top of another & default]

dim = 1 results in a tensor of one 3 x 2 x 4 tensors and so on...

## HSTACK & VSTACK

torch.hstack() -> stacks horizontally
torch.vstack() -> stacks vertically


In [179]:
x = torch.tensor([[1,2,3], [3,2,1]])
y = torch.tensor([[4,5,6], [6,5,4]])
z = torch.tensor([[7,8,9], [9,8,7]])

torch.hstack((x, y, z)), torch.vstack((x, y, z))

(tensor([[1, 2, 3, 4, 5, 6, 7, 8, 9],
         [3, 2, 1, 6, 5, 4, 9, 8, 7]]),
 tensor([[1, 2, 3],
         [3, 2, 1],
         [4, 5, 6],
         [6, 5, 4],
         [7, 8, 9],
         [9, 8, 7]]))

## SQUEEZE and UNSQUEEZE

squeeze() and unsqueeze() are tensor operations used to remove or add dimensions of size 1 from tensors.

Syntax: tensor.squeeze(dim=None)

If dim is not specified, it removes all dimensions of size 1.
If dim is specified, it only removes that specific dimension if its size is 1. If the size is not 1, it raises an error.

For example, if input is of shape: 
(A×1×B×C×1×D) then the input.squeeze() will be of shape: 
(A×B×C×D).

Syntax: tensor.unsqueeze(dim)

The dim parameter is where the new size 1 dimension will be added. The index of dim can be negative (starting from the last dimension).

In [180]:
x = torch.rand(3, 1, 1, 2, 1)
x, x.shape

(tensor([[[[[0.3789],
            [0.9864]]]],
 
 
 
         [[[[0.8655],
            [0.0681]]]],
 
 
 
         [[[[0.1279],
            [0.6471]]]]]),
 torch.Size([3, 1, 1, 2, 1]))

In [181]:
SqueezedX = x.squeeze()
SqueezedX2 = torch.squeeze(x)
SqueezedX, SqueezedX2, SqueezedX.shape

(tensor([[0.3789, 0.9864],
         [0.8655, 0.0681],
         [0.1279, 0.6471]]),
 tensor([[0.3789, 0.9864],
         [0.8655, 0.0681],
         [0.1279, 0.6471]]),
 torch.Size([3, 2]))

In [182]:
newX = torch.rand(1, 7)
newUnSqueezedX = newX.unsqueeze(dim = 1)    #Adds a dimension at the specified index
newUnSqueezedX2 = torch.unsqueeze(newX, dim = 1)
newX, newUnSqueezedX, newUnSqueezedX2, newUnSqueezedX.shape

(tensor([[0.8727, 0.9868, 0.5519, 0.9232, 0.0992, 0.2315, 0.6114]]),
 tensor([[[0.8727, 0.9868, 0.5519, 0.9232, 0.0992, 0.2315, 0.6114]]]),
 tensor([[[0.8727, 0.9868, 0.5519, 0.9232, 0.0992, 0.2315, 0.6114]]]),
 torch.Size([1, 1, 7]))

Returns a view of the original tensor input with its dimensions permuted.

Parameters
input (Tensor) – the input tensor.

dims (tuple of int) – The desired ordering of dimensions

Since permute() returns a view, any change on the permutation will reflect on the actual tensor

In [ ]:
newT = torch.rand(3, 2, 1)

permutedT = newT.permute(2, 0, 1)  #Shifts the 0th dimension to 2nd, 1st to 0th and 2nd to 1st
newT.shape, newT, permutedT.shape, permutedT


(torch.Size([3, 2, 1]),
 tensor([[[0.2172],
          [0.7482]],
 
         [[0.9270],
          [0.7055]],
 
         [[0.1485],
          [0.7263]]]),
 torch.Size([1, 3, 2]),
 tensor([[[0.2172, 0.7482],
          [0.9270, 0.7055],
          [0.1485, 0.7263]]]))

## Accessing Elements by Index

In [186]:
idxTensor = torch.arange(1, 10).reshape(1, 3, 3)
idxTensor

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [188]:
#Access by Index
idxTensor[0][2][0]

tensor(7)

In [197]:
#Access all values of a common dimension with ":" operator
idxTensor[0][2][:], idxTensor[0][:][0], idxTensor[0][2]

(tensor([7, 8, 9]), tensor([1, 2, 3]), tensor([7, 8, 9]))

idxTensor[0][2][ : ] tries to select all values of idxTensor[0][2]

idxTensor[0][ : ][0] tries to select all values of idxTensor[0], which is the whole 3x3 matrix. Then the last index [0] picks the first row from there, which is tensor([1, 2, 3])